In [1]:
import numpy as np

np_array = np.arange(100, 200, 10).reshape(5, 2)
np_array


[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [2]:
sampleArray = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [3]:
third_column = sampleArray[:, 2]
third_column

array([33, 66, 99])

In [4]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
sum_array = arrayOne + arrayTwo
sum_array

array([[20, 39, 33],
       [25, 25, 28]])

In [5]:
square_sum = sum_array ** 2
square_sum

array([[ 400, 1521, 1089],
       [ 625,  625,  784]])